# workspace is in rust
[workspace]
members = ["backstitch", "backstitch_godot"]
resolver = "3"

[workspace.package]
version = "3.0.0"


# create profile release_debug
[profile.release_debug]
inherits = "release"
opt-level = 0
strip = "none"
debug = true
lto = false
panic = "abort"
codegen-units = 1
panic-strategy = "abort"
#config flag "release_debug"

# set release_debug as default profile
default = ["release_debug"]

[workspace.dependencies]
godot = { version = "0.5.4", features = ["experimental-threads"] }
uuid = "1.5.0"
automerge = "0.9.0"
autosurgeon = { git = "https://github.com/LilithSilver/autosurgeon.git", branch = "upgrade-automerge" }
futures = "0.3.31"
samod = { git = "https://github.com/LilithSilver/samod.git", branch = "update-tungstenite-v10", features = [
    "tokio",
    "threadpool",
    "tungstenite",
] }
safer-ffi = "0.1.13"
regex = "1.12.2"
tokio = { version = "1.49.0", features = ["full"] }
console-subscriber = { version = "0.5.0" }
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.23", features = ["env-filter", "json"] }
tracing-appender = "0.2.2"
tracing-panic = "0.1.2"
