name: Godot Backstitch Plugin Build
description: Build Godot plugin for Backstitch.

inputs:
  arch:
    required: true
    default: ''
    description: Rust target platform.
  
runs:
  using: composite
  steps:
    - uses: extractions/setup-just@v3
    - name: Install Rust
      uses: actions-rust-lang/setup-rust-toolchain@v2
      with:
        target: ${{ inputs.arch }}
        cache-key: backstitch_rust_plugin-${{ inputs.arch }}
    - name: Add additional arm64 target for macOS
      shell: sh
      if: ${{ inputs.arch == 'x86_64-apple-darwin'}}
      run: |
        rustup target add aarch64-apple-darwin
    - name: Show targets
      shell: sh
      run: |
        rustc --print=target-list
    - name: Build for Windows and Linux
      shell: sh
      env:
        CI: 1
      if: ${{ inputs.arch != 'x86_64-apple-darwin'}}
      run: |
        just build-backstitch release ${{ inputs.arch }}
    - name: Build for Mac
      shell: sh
      env:
        CI: 1
      if: ${{ inputs.arch == 'x86_64-apple-darwin'}}
      run: |
        just build-backstitch release "all-apple-darwin"
    - name: Copy to release
      shell: sh
      run: |
        mkdir -p target/release
        rm -rf target/release
        cp -rf target/${{ inputs.arch }}/release target/release
