#!/usr/bin/env python
import re
import shutil
from subprocess import Popen, PIPE

Import("env")
Import("env_modules")

env_backstitch_editor = env_modules.Clone()
env_backstitch_editor["disable_exceptions"] = False

env_backstitch_editor.Append(CPPPATH=["."])


def doproc(cmd):
    # ensure that it doesn't print stderr to the terminal if print_err is False
    process = Popen(cmd, stdout=PIPE, stderr=PIPE)
    (output, err) = process.communicate()
    if not err:
        return output.decode("utf-8").strip()
    else:
        return None


module_obj = []

env_backstitch_editor.add_source_files(module_obj, "*.cpp")
# build_backstitch_rust(module_obj)
env.modules_sources += module_obj
