name: Install Backstitch launcher
description: Installs inkandswitch/backstitch-launcher into project.
inputs:
  project_path:
    required: true
    description: Project path to install launcher into.

runs:
  using: composite
  steps:
    - uses: robinraju/release-downloader@v1
      with:
        repository: 'inkandswitch/backstitch-launcher'
        tag: 'v1.0.1'
        fileName: 'backstitch-launcher-*.zip'
        out-file-path: 'backstitch-launcher'
        extract: true
    - name: Set chmod
      shell: bash
      run: |
        chmod a+x ./backstitch-launcher/backstitch-launcher-linux
        chmod a+x ./backstitch-launcher/backstitch-launcher-macos.app/Contents/MacOS/backstitch-launcher-macos
    - name: Copy exe files
      shell: bash
      run: |
        cp ./backstitch-launcher/backstitch-launcher-windows.exe ${{ inputs.project_path }}
        cp ./backstitch-launcher/backstitch-launcher-linux ${{ inputs.project_path }}
        cp -R ./backstitch-launcher/backstitch-launcher-macos.app ${{ inputs.project_path }}
    - name: Merge .gitignore
      shell: bash
      run: cat ./backstitch-launcher/.gitignore.template >> ${{ inputs.project_path }}/.gitignore
    - name: Write .backstitch_version
      shell: bash
      run: echo "${{ github.ref_name }}" >> ${{ inputs.project_path }}/.backstitch_version


