name: Install Backstitch launcher
description: Installs inkandswitch/backstitch-launcher into project.
inputs:
  project_path:
    required: true
    description: Project path to install launcher into.
  version:
    required: true
    description: Version of the launcher to install
  godot_version:
    required: true
    description: Version of Godot to set the launcher to

runs:
  using: composite
  steps:
    - uses: robinraju/release-downloader@v1
      with:
        repository: 'inkandswitch/backstitch-launcher'
        tag: ${{ inputs.version }}
        fileName: 'backstitch-launcher-*.zip'
        out-file-path: 'backstitch-launcher'
        extract: true
    - name: Set chmod
      shell: bash
      run: |
        chmod a+x ./backstitch-launcher/backstitch-launcher-linux
        chmod a+x ./backstitch-launcher/backstitch-launcher-macos.app/Contents/MacOS/backstitch-launcher
    - name: Copy exe files
      shell: bash
      run: |
        cp ./backstitch-launcher/backstitch-launcher-windows.exe ${{ inputs.project_path }}
        cp ./backstitch-launcher/backstitch-launcher-linux ${{ inputs.project_path }}
        cp -R ./backstitch-launcher/backstitch-launcher-macos.app ${{ inputs.project_path }}
    - name: Merge .gitignore
      shell: bash
      run: cat ./backstitch-launcher/.gitignore.template >> ${{ inputs.project_path }}/.gitignore
    - name: Compute version
      shell: bash
      run: |
        CURRENT_RELEASE=$(git -C backstitch-tmp describe --tags "$(git -C backstitch-tmp rev-list --tags --max-count=1)")

        if [[ "${{ github.ref_type }}" == "tag" ]]; then
          VERSION="${{ github.ref_name }}"
        else
          VERSION="${CURRENT_RELEASE}/${{ github.ref_name }}"
        fi

        echo "VERSION=$VERSION" >> "$GITHUB_ENV"
    - name: Write .backstitch_version
      shell: bash
      run: |
        cat <<EOF > ${{ inputs.project_path }}/.backstitch_version
        {"backstitch_version":"$VERSION","godot_version":""}
        EOF

