name: 🧵 Compose Projects
on:
  workflow_call:

jobs:
  # Grab the environment variables from build.env and output them
  # Do this in a separate job here since we wanna use it for the next job's matrix
  load-env:
    name: 🔍 Load Environment variables
    runs-on: "ubuntu-latest"
    outputs:
      THREADBARE_REPO: ${{ steps.dotenv.outputs.THREADBARE_REPO }}
      THREADBARE_REF: ${{ steps.dotenv.outputs.THREADBARE_REF }}
      MODDABLE_PLATFORMER_REPO: ${{ steps.dotenv.outputs.MODDABLE_PLATFORMER_REPO }}
      MODDABLE_PLATFORMER_REF: ${{ steps.dotenv.outputs.MODDABLE_PLATFORMER_REF }}
      MODDABLE_PONG_REPO: ${{ steps.dotenv.outputs.MODDABLE_PONG_REPO }}
      MODDABLE_PONG_REF: ${{ steps.dotenv.outputs.MODDABLE_PONG_REF }}
      RECOMMENDED_LAUNCHER: ${{ steps.dotenv.outputs.RECOMMENDED_LAUNCHER }}
    steps:
      - uses: actions/checkout@v7
      - id: dotenv
        uses: falti/dotenv-action@v1.1.5
        with:
          path: build.env
          keys-case: bypass

  compose-projects:
    needs: [load-env]
    runs-on: "ubuntu-latest"
    name: 🪡 Compose ${{ matrix.project.name }}
    strategy:
      fail-fast: false
      matrix:
        project:
          - name: threadbare
            repo: ${{ needs.load-env.outputs.THREADBARE_REPO }}
            ref: ${{ needs.load-env.outputs.THREADBARE_REF }}
            lfs: true
          - name: moddable-platformer
            repo: ${{ needs.load-env.outputs.MODDABLE_PLATFORMER_REPO }}
            ref: ${{ needs.load-env.outputs.MODDABLE_PLATFORMER_REF }}
            lfs: false
          - name: moddable-pong
            repo: ${{ needs.load-env.outputs.MODDABLE_PONG_REPO }}
            ref: ${{ needs.load-env.outputs.MODDABLE_PONG_REF }}
            lfs: false
    steps:
      - name: Checkout project
        uses: actions/checkout@v6
        with:
          repository: ${{ matrix.project.repo }}
          ref: ${{ matrix.project.ref }}
          path: ${{ matrix.project.name }}
          lfs: ${{ matrix.project.lfs }}
          fetch-depth: 0
          persist-credentials: false
      - name: Download Backstitch
        uses: actions/download-artifact@v7
        with:
          pattern: backstitch
          path: backstitch-extract
      - name: Checkout backstitch # for actions
        uses: actions/checkout@v6
        with:
          fetch-depth: 0
          path: backstitch-tmp
          repository: inkandswitch/backstitch
      - name: Write backstitch.cfg
        run: |
          cat <<'EOF' > ${{ matrix.project.name }}/backstitch.cfg
          [backstitch]
          server_url="alpha.backstitch.dev:8085"
          available_servers="alpha.backstitch.dev:8085"
          EOF
      - name: Compute version
        shell: bash
        run: |
          CURRENT_RELEASE=$(git -C backstitch-tmp describe --tags "$(git -C backstitch-tmp rev-list --tags --max-count=1)")

          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            VERSION="${{ github.ref_name }}"
          else
            VERSION="${CURRENT_RELEASE}+${{ github.ref_name }}"
          fi

          echo "VERSION=$VERSION" >> "$GITHUB_ENV"
      - name: Write .backstitch_version
        run: |
          cat <<'EOF' > ${{ matrix.project.name }}/.backstitch_version
          {"backstitch_version":"${VERSION}","godot_version":"0.0"}
          EOF
      - name: Copy to addons
        shell: sh
        run: |
          mkdir -p ${{ matrix.project.name }}/addons/backstitch
          cp -r backstitch-extract/addons/backstitch/. ${{ matrix.project.name }}/addons/backstitch
      - name: Install Backstitch Launcher
        uses: ./backstitch-tmp/.github/actions/install-launcher
        with:
          project_path: ${{ matrix.project.name }}
          version: v${{ needs.load-env.outputs.RECOMMENDED_LAUNCHER }}
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          include-hidden-files: true
          name: ${{ matrix.project.name }}-with-backstitch
          path: |
            ${{ matrix.project.name }}
          if-no-files-found: error
